cache:
  paths:
  - node_modules/
before_script:
  - npm install
lint:
  script:
  - npm run tslint
build:
  script:
  - npm run build-release
    artifacts:
    paths:
    - dist/docs
    name: "arlas-web-core-doc"




