language: node_js
node_js:
  - "8"

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules/

jobs:
  include:
    - before_script: yarn global add tslint typescript
      script: npm run tslint
    - script:
      - npm install
      - npm run build-release; mv dist/docs .
    - script: ./mkDocs.sh
