language: node_js
node_js:
  - "16"

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules/

jobs:
  include:
    - before_script: npm install -g tslint typescript
      env:
        - job=lint
      script: npm run tslint
    - env:
        - job=build_release
      script:
      - npm install
      - npm run build-release
    - env:
        - job=generate_documentation
      script: ./mkDocs.sh
